
# Change to true if you want to store data in mysql database
# If false plugin will store data in yml files
ues_mysql: false

# mysql connection data
mysql:
    database: Database_name
    username: Username
    password: Password
    host: Host_Name
    port: Port
    table: Player_data_table_Name
    
