#
# Dont use config file
# Work in progress 
# ues_mysql HAVE TO be false
# WORK IN PROGRESSS :)
#
ues_mysql: false
mysql:
    database: Database_name
    username: Username
    password: Password
    host: Host_Name
    port: Port
    table: Player_data_table_Name
    
