name: DigLoot
version: 1.1.0
main: me.Dremnor.DigLoot.Main
description: Random loot form block breaking
author: Dremnor
api-version: 1.14
commands:
    dl:
        description: Main DigLoot Command
        usage: /dl