name: DigLoot
version: 1.3.1
main: me.Dremnor.DigLoot.Main
description: Random loot form diging
author: Dremnor
api-version: 1.14
commands:
    dl:
        description: Main DigLoot Command
        usage: /dl